name: gc_course_env
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - triangle
    - opencv-python
    - gmsh
  - igl
  - matplotlib
  - jupyterlab
  - pytest
  - pytest-html
  - pytest-timeout
  - matplotlib
  - svgwrite
  - meshplot
  - pyvista
